#!/bin/bash
# Setup Traefik Dynamic Config für Kalku
# Verwendung: ./scripts/setup-traefik.sh [domain]
# Beispiel:   ./scripts/setup-traefik.sh kalku.layer-one.io

set -e

DOMAIN="${1:-kalku.layer-one.io}"
CONFIG_DIR="/etc/dokploy/traefik/dynamic"
CONFIG_FILE="$CONFIG_DIR/kalku.yml"

# Service finden
SERVICE_NAME=$(docker service ls --format '{{.Name}}' | grep 'kalku-kalku-' | grep -v 'labels' | head -1)

if [ -z "$SERVICE_NAME" ]; then
  echo "Error: Kein Kalku Service gefunden"
  exit 1
fi

echo "Found service: $SERVICE_NAME"
echo "Domain: $DOMAIN"
echo "Config file: $CONFIG_FILE"

# Traefik Dynamic Config erstellen
cat > "$CONFIG_FILE" << EOF
# Traefik Dynamic Configuration for Kalku
# Auto-generated by setup-traefik.sh

http:
  routers:
    kalku:
      rule: "Host(\`$DOMAIN\`)"
      entryPoints:
        - websecure
      service: kalku
      tls:
        certResolver: letsencrypt

  services:
    kalku:
      loadBalancer:
        servers:
          - url: "http://$SERVICE_NAME:3001"
EOF

echo "Traefik config created at $CONFIG_FILE"
echo ""
echo "Content:"
cat "$CONFIG_FILE"
echo ""
echo "Traefik will auto-reload the config. Test: https://$DOMAIN"
